### PR TITLE
Update flysystem to the next major version

### PR DESCRIPTION
**Pull request by rtuin**
## Test

Run `$ phpunit` and notice all tests (still) pass

### CODE REVIEW

**Comment by dennisdegreef** [comment]
Oh they do? Might even remove my own class extends then... That was due to the fact that this version had the same interface for `Filesystem` and `Adapter`.

Awesome! :+1: thanks!

**Comment by dennisdegreef** [comment]
See comment in docblock at https://github.com/link0/profiler/blob/master/src/Link0/Profiler/FilesystemInterface.php

`FilesystemInterface.php` and `Filesystem.php` can both be removed then I guess :)

**Comment by dennisdegreef** [comment]
Reran tests, thought they'd might fail because of #65 , but it only failed on `No releases available for package "pecl.php.net/xhprof"` on `php5.5` :s

**Comment by rtuin** [comment]
I've removed your local filesystem ports and replaced them by the Flysystem interface directly.
"Works on my machine!"

**Comment by dennisdegreef** [comment]
Thanks! :)

Could you maybe also change the README.md?
```php
// [...]
$filesystem = new \Link0\Profiler\Filesystem($filesystemAdapter);
// [...]
```

**Comment by rtuin** [comment]
Great idea, forgot about that. I've updated `README.md` and rebased against master.

**Pull request merged**
