### PR TITLE
Rewrote internal Profile data storage to be more portable and be able to... [WIP]

### PR DESCRIPTION
**Pull request by dennisdegreef**
... contain also Application and Server information later on

Work in progress on internal data structure rewrite.
This is a backwards compatible break and will be the base for v1.x

### CODE REVIEW

**Comment by dennisdegreef** [comment]
@lonelypullrequests

**Comment by dennisdegreef** [comment]
@lonelypullrequests

**Comment by reenl** [comment]
As I see it, the Serializer class is only used for serializing the profile, so maybe it should be able to accept the Profiler directly.

Other options might be:
- Wrap the serializer in a ProfileSerializer.
- Create Serializable (interface with fromArray() and toArray()), let the profile implement it and make the Serializer compatible.

**Comment by dennisdegreef** [comment]
Rebased from master

**Pull request merged**
